name: Code quality

on:
    push:
        branches: [main]
        paths:
            - "functions/**"
            - ".github/workflows/biome-reviewdog.yml"
    pull_request:
        branches: [main]
        paths:
            - "functions/**"
            - ".github/workflows/biome-reviewdog.yml"

jobs:
    quality:
        defaults:
            run:
                working-directory: functions
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Biome
              uses: biomejs/setup-biome@v2
              with:
                  version: latest
            - name: Run Biome
              run: biome ci .
